theme: jekyll-theme-minimal
title: Hacker Cat Ninja
description: > # this means to ignore newlines until "baseurl:"
    Coding & Security<br><br><img src="/assets/img/avatar.png" alt="avatar" width="150" height="150"><br>
baseurl: ""
url: "https://blog.hackercat.ninja"
# logo: /assets/img/avatar.png
