theme: jekyll-theme-minimal
title: HackerCat Ninja
description: > # this means to ignore newlines until "baseurl:"
    &emsp;&emsp;&emsp;Coding & Security<br><br>&emsp;&emsp;<img src="/assets/img/avatar.png" alt="avatar" width="150" height="150"><br>
baseurl: ""
url: "https://blog.hackercat.ninja"
# logo: /assets/img/avatar.png
